export const LOTR_NAMES = [
    'Aegnor',
    'Aerin',
    'Alfrid',
    'Algund',
    'Amandil',
    'Amis',
    'Amras',
    'Amrod',
    'Anairë',
    'Andróg',
    'Angrod',
    'Arador',
    'Aragorn',
    'Aratar',
    'Arathorn',
    'Aredhel',
    'Arien',
    'Arveleg I',
    'Arwen',
    'Azog',
    'Bain',
    'Balin',
    'Bandobras Touque',
    'Barahir',
    'Bard',
    'Beleg Cúthalion',
    'Bell Bonenfant',
    'Belladone Touque',
    'Beorn',
    'Beren',
    'Berethor',
    'Bifur',
    'Bilbon Sacquet',
    'Bofur',
    'Bolg',
    'Bombur',
    'Boromir',
    'Brand',
    'Brandir',
    'Bregolas',
    'Bregor',
    'Brûz',
    'Bungo Sacquet',
    'Caranthir',
    'Carnán',
    'Celeborn (Elfe)',
    'Celebrimbor',
    'Celebrían',
    'Celegorm',
    'Curufin',
    'Círdan',
    'Denethor I',
    'Dior',
    'Dirhael',
    'Dori',
    'Dorlas',
    'Drogon Sacquet',
    'Dwalin',
    'Dáin II',
    'Déagol',
    'Elanor',
    'Eldarion',
    'Elegost',
    'Elendil',
    'Elfwine',
    'Elladan',
    'Elrohir',
    'Elrond',
    'Elros',
    'Eluréd et Elurín',
    'Elwing',
    'Emeldir',
    'Erkenbrand',
    'Eru Ilúvatar',
    'Estë',
    'Evranï',
    'Eärendil',
    'Eöl',
    'Eönwë',
    'Faramir',
    'Fengel',
    'Figwit',
    'Fili',
    'Fili le nain',
    'Finarfin',
    'Fingolfin',
    'Fingon',
    'Finrod',
    'Finwë',
    'Frodon Sacquet',
    'Frór',
    'Fëanor',
    'Galadriel',
    'Galdor',
    'Gamelin',
    'Gandalf',
    'Gelmir',
    'Gil-galad',
    'Gildor',
    'Gilmith',
    'Gilraen',
    'Gimli',
    'Girion',
    'Glaurung',
    'Glorfindel',
    'Glóin',
    'Gollum',
    'Grimbeorn',
    'Gríma',
    'Grór',
    'Gwindor',
    'Gárulf',
    'Gérontius Touque',
    'Hador',
    'Haldir',
    'Halmir',
    'Handir',
    'Hareth',
    'Helm Main-Marteau',
    'Huor',
    'Háma',
    'Húrin Thalion',
    'Ibun',
    'Idril',
    'Irmo',
    'Isildur',
    'Istari',
    'Ithryn Luin',
    'Khamûl',
    'Khîm',
    'Kili',
    'Legolas',
    'Lindir',
    'Lurtz',
    'Lúthien',
    'Maedhros',
    'Maeglin',
    'Maglor',
    'Mandos',
    'Manwë',
    'Melian',
    'Meriadoc Brandebouc',
    'Morgoth',
    'Morwen',
    'Mîm',
    'Nerdanel',
    'Nessa',
    'Nienna',
    'Nimloth',
    'Niënor',
    'Nori',
    'Olwë',
    'Ori',
    'Orleg',
    'Oromë',
    'Ossë',
    'Peregrin Touque',
    'Primula Brandebouc',
    'Prince Imrahil',
    'Père Magotte',
    'Radagast',
    'Ratbag',
    'Rohirrim',
    'Roi Gobelin',
    "Roi-sorcier d'Angmar",
    'Rois du Gondor',
    'Rosie Chaumine',
    'Rían',
    'Sador',
    'Saeros',
    'Samsagace Gamegie',
    'Saroumane',
    'Sauron',
    'Sigrid',
    'Sindar',
    'Smaug',
    "Suladân l'immortel",
    'Sylvebarbe',
    'Talion',
    'Tar Goroth',
    'Tauriel',
    'Teleri',
    'Thengel',
    'Theodred',
    'Thingol',
    'Thorin I',
    'Thorin II Écu-de-Chêne',
    'Thorin III Heaume-De-Pierre',
    'Thranduil',
    'Thráin II',
    'Thrór',
    'Théoden',
    'Théodred',
    'Tilda',
    'Tilion',
    'Tom Bombadil',
    'Tour de Sauron',
    'Tulkas',
    'Tuor',
    'Turgon',
    'Túrin Turambar',
    'Uinen',
    'Ulmo',
    'Ungoliant',
    'Uruk-hai',
    'Urwen',
    'Vairë',
    'Vanyar',
    'Vieil Homme-Saule',
    'Vána',
    'Yavanna',
    'Éomer',
    'Éowyn',
    'Óin',
]
